#!/usr/bin/env python3
"""Make the Sign metatile (id 125) interactable: pressing A while facing a Sign
shows a PokemonDisplayPreset message describing the current area.

Implementation:
  * variables.gbsres : add global var 22 "CurrentArea".
  * scripts/read_area_sign.gbsres : new custom event; switches on CurrentArea and
    shows the matching area's signboard text.
  * init_overworld_script.gbsres : inside the existing A-button handler (which
    already reads the metatile in front into var 0), add a branch
    `if MetatileId == SIGN -> call Read Area Sign`.
  * every overworld scene On Init : set CurrentArea to that scene's area number.
"""
import json, os, glob, uuid

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "project"))

PRESET_ID  = "b5f85a5b-5f40-4355-9e63-db5ce2bfe0bc"
SIGN_CONST = "edef1b1d-4243-4a9f-897b-b3b3b45c1a87"   # METATILEIDS/SIGN = 125
INIT_ID    = "70823794-eb52-4bb1-83a1-d0a628f22deb"   # Init Overworld Script
GET_MT_ID  = "d257302a-ec07-46f5-a275-9a4e9d7edee0"   # EVENT_GET_META_TILE_AT_POS in A-handler
AREA_VAR   = "22"
READ_SIGN_ID = "f0a1b2c3-d4e5-4f60-8a1b-2c3d4e5f6071"  # stable id for Read Area Sign

PRESET_ARGS = {
    "minHeight": 6, "maxHeight": 6, "textX": 1, "textY": 1, "textHeight": 4,
    "position": "bottom", "clearPrevious": True, "showFrame": "true",
    "speedIn": -3, "speedOut": -3, "closeWhen": "key", "closeButton": "a",
    "closeDelayTime": 0.5, "closeDelayFrames": 30,
}

# Ordered scene -> signboard lines (area numbers assigned by this order, 1..38).
# Location name header in caps (signboard style); slogan in sentence case.
AREAS = [
    ("palette_town",   ["PALLET TOWN", "Shades of your", "journey await!"]),
    ("viridian_city",  ["VIRIDIAN CITY", "The eternally", "green paradise."]),
    ("pewter_city",    ["PEWTER CITY", "A stone gray city."]),
    ("cerulean_city",  ["CERULEAN CITY", "A mysterious,", "blue aura town."]),
    ("vermillion_city",["VERMILION CITY", "Port of exquisite", "sunsets."]),
    ("lavender_town",  ["LAVENDER TOWN", "The noble", "purple town."]),
    ("celadon_city",   ["CELADON CITY", "City of rainbow", "dreams."]),
    ("fuchsia_city",   ["FUCHSIA CITY", "Behold! Passion", "pink!"]),
    ("saffron_city",   ["SAFFRON CITY", "Golden land of", "commerce."]),
    ("cinabar_island", ["CINNABAR ISLAND", "Fiery town of", "burning desire."]),
    ("indigo_plateau", ["INDIGO PLATEAU", "Pokemon League", "front."]),
    ("route_1",  ["ROUTE 1", "Pallet Town -", "Viridian City"]),
    ("route_2",  ["ROUTE 2", "Viridian City -", "Pewter City"]),
    ("route_3",  ["ROUTE 3", "Pewter City -", "Mt. Moon"]),
    ("route_4",  ["ROUTE 4", "Mt. Moon -", "Cerulean City"]),
    ("route_5",  ["ROUTE 5", "Cerulean City -", "Saffron City"]),
    ("route_6",  ["ROUTE 6", "Saffron City -", "Vermilion City"]),
    ("route_7",  ["ROUTE 7", "Celadon City -", "Saffron City"]),
    ("route_8",  ["ROUTE 8", "Saffron City -", "Lavender Town"]),
    ("route_9",  ["ROUTE 9", "Cerulean City -", "Rock Tunnel"]),
    ("route_10", ["ROUTE 10", "Rock Tunnel -", "Lavender Town"]),
    ("route_11", ["ROUTE 11", "Vermilion City -", "Route 12"]),
    ("route_12", ["ROUTE 12", "Lavender Town -", "Route 13"]),
    ("route_13", ["ROUTE 13", "Route 12 -", "Route 14"]),
    ("route_14", ["ROUTE 14", "Route 13 -", "Route 15"]),
    ("route_15", ["ROUTE 15", "Route 14 -", "Fuchsia City"]),
    ("route_16", ["ROUTE 16", "Celadon City -", "Cycling Road"]),
    ("route_17a",["ROUTE 17", "Cycling Road", "(north end)"]),
    ("route_17b",["ROUTE 17", "Cycling Road", "(south end)"]),
    ("route_18", ["ROUTE 18", "Cycling Road -", "Fuchsia City"]),
    ("route_19", ["ROUTE 19", "Fuchsia City -", "the open sea"]),
    ("route_20", ["ROUTE 20", "Seafoam Islands -", "Cinnabar Island"]),
    ("route_21", ["ROUTE 21", "Cinnabar Island -", "Pallet Town"]),
    ("route_22", ["ROUTE 22", "Viridian City -", "Victory Road"]),
    ("route_23_a",["ROUTE 23", "Victory Road", "checkpoint (A)"]),
    ("route_23_b",["ROUTE 23", "Victory Road", "checkpoint (B)"]),
    ("route_24", ["ROUTE 24", "Cerulean City -", "Nugget Bridge"]),
    ("route_25", ["ROUTE 25", "Nugget Bridge -", "the sea cape"]),
]

# Per-coordinate signs WITHIN a scene. Keyed by the faced metatile's top-left
# tile coords (x, y) — the values the A-handler leaves in vars 12 / 13. Any sign
# tile NOT listed here falls back to the scene's area sign above.
#
# Generated by tools/derive_signs.py from the gb-studio-cli export: every Sign
# metatile (id 125) is found in each scene's compiled half-res metatile map
# (cell (mx,my) -> faced coord (2*mx, 2*my)) and labelled by its nearest named
# building-door trigger (Gym, Mart, Center, Lab, etc.). Town / route marker signs
# (no building nearby) are intentionally left to the area-sign fallback.
SCENE_SIGNS = {
    'palette_town': [
        (6, 10, ['YOUR HOUSE', 'Home, sweet home.']),
        (22, 10, ["RIVAL'S HOUSE", 'Your rival lives', 'here.']),
        (26, 26, ["OAK'S LAB", 'Pokemon research', 'happens here!']),
    ],
    'viridian_city': [
        (34, 34, ['PRIVATE HOME', 'Someone lives', 'here.']),
        (42, 58, ['POKE MART', 'Buy useful goods', 'for your trip.']),
        (54, 14, ['POKEMON GYM', 'A tough battle', 'awaits inside!']),
    ],
    'pewter_city': [
        (22, 34, ['PRIVATE HOME', 'Someone lives', 'here.']),
        (30, 18, ['MUSEUM', 'Of science.', 'Fossils within!']),
        (38, 58, ['POKEMON CENTER', 'Heal your tired', 'Pokemon here!']),
        (50, 46, ['PRIVATE HOME', 'Someone lives', 'here.']),
        (66, 38, ['PEWTER GYM', 'Leader: Brock', 'Rock types!']),
    ],
    'cerulean_city': [
        (22, 50, ['BIKE SHOP', 'Wheels for your', 'adventure!']),
        (46, 38, ['POKEMON CENTER', 'Heal your tired', 'Pokemon here!']),
        (54, 42, ['CERULEAN GYM', 'Leader: Misty', 'Water types!']),
    ],
    'vermillion_city': [
        (14, 26, ['VERMILION GYM', 'Leader: Lt. Surge', 'Electric types!']),
        (14, 38, ['PRIVATE HOME', 'Someone lives', 'here.']),
        (58, 30, ['POKE MART', 'Buy useful goods', 'for your trip.']),
    ],
    'lavender_town': [
        (10, 18, ['POKEMON CENTER', 'Heal your tired', 'Pokemon here!']),
        (18, 6, ['VOLUNTEER HOUSE', 'Helping Pokemon', 'in need.']),
        (22, 18, ['POKE MART', 'Buy useful goods', 'for your trip.']),
        (34, 14, ['POKEMON TOWER', 'Rest in peace,', 'lost Pokemon.']),
    ],
    'celadon_city': [
        (26, 58, ['POKEMON CENTER', 'Heal your tired', 'Pokemon here!']),
        (42, 18, ['DEPT. STORE', 'Floors full of', 'Pokemon goods!']),
        (54, 42, ['DEPT. STORE', 'Floors full of', 'Pokemon goods!']),
        (66, 42, ['DEPT. STORE', 'Floors full of', 'Pokemon goods!']),
    ],
    'fuchsia_city': [
        (10, 58, ['POKEMON CENTER', 'Heal your tired', 'Pokemon here!']),
        (14, 14, ['FUCHSIA GYM', 'Leader: Koga', 'Poison types!']),
        (34, 10, ['SAFARI ZONE', 'Catch rare', 'Pokemon inside!']),
        (42, 30, ["WARDEN'S HOME", 'Keeper of the', 'Safari Zone.']),
        (54, 58, ['SAFARI ZONE', 'Catch rare', 'Pokemon inside!']),
    ],
    'saffron_city': [
        (30, 42, ['SILPH CO.', 'Makers of fine', 'Pokemon gear.']),
        (54, 10, ['SILPH CO.', 'Makers of fine', 'Pokemon gear.']),
        (54, 58, ['POKEMON CENTER', 'Heal your tired', 'Pokemon here!']),
        (70, 10, ['SILPH CO.', 'Makers of fine', 'Pokemon gear.']),
    ],
    'cinabar_island': [
        (18, 10, ['POKEMON LAB', 'Research in', 'progress.']),
        (18, 22, ['CINNABAR GYM', 'Leader: Blaine', 'Fire types!']),
        (26, 6, ['POKEMON LAB', 'Research in', 'progress.']),
    ],
    'route_2': [
        (22, 22, ["DIGLETT'S CAVE", 'A tunnel for', 'small Pokemon.']),
    ],
    'route_4': [
        (34, 14, ['PRIVATE HOME', 'Someone lives', 'here.']),
    ],
    'route_11': [
        (2, 10, ["DIGLETT'S CAVE", 'A tunnel for', 'small Pokemon.']),
    ],
    'route_25': [
        (86, 6, ["BILL'S HOUSE", 'The PokeManiac', 'lives here.']),
    ],
}

for _, lines in AREAS:
    for l in lines:
        assert len(l) <= 18, f"sign line too long ({len(l)}): {l}"
for scene, signs in SCENE_SIGNS.items():
    for x, y, lines in signs:
        if lines is None:        # None = show the scene's area/town name sign
            continue
        for l in lines:
            assert len(l) <= 18, f"sign line too long ({len(l)}): {l}"

def uid():
    return str(uuid.uuid4())

def text_args(lines):
    a = {"__presetId": PRESET_ID, "text": ["\n\n".join(lines)],
         "__section": "presets", "avatarId": ""}
    a.update(PRESET_ARGS)
    return a

def load(f):
    with open(f, encoding="utf-8") as fh:
        return json.load(fh)

def save(f, d):
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(d, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

# ---------------------------------------------------------------- 1. variable 22
def ensure_variable():
    f = os.path.join(ROOT, "variables.gbsres")
    d = load(f)
    if not any(v["id"] == AREA_VAR for v in d["variables"]):
        # insert right after var 21 to keep numeric ordering
        idx = next(i for i, v in enumerate(d["variables"]) if v["id"] == "21") + 1
        d["variables"].insert(idx, {"id": AREA_VAR, "name": "CurrentArea",
                                    "symbol": "var_currentarea"})
        save(f, d)
        return "added"
    return "exists"

# ---------------------------------------------------------- 2. read_area_sign event
def build_switch(cases):
    """cases: list of (area_num, children_list). Chained EVENT_SWITCH, 16 per level."""
    chunk = cases[:16]
    rest = cases[16:]
    args = {"variable": AREA_VAR, "choices": len(chunk), "__collapseElse": False}
    for i in range(16):
        args[f"__collapseCase{i}"] = False
    for i, (num, _) in enumerate(chunk):
        args[f"value{i}"] = {"type": "number", "value": num}
    children = {}
    for i, (_, body) in enumerate(chunk):
        children[f"true{i}"] = body
    children["false"] = [build_switch(rest)] if rest else []
    return {"command": "EVENT_SWITCH", "args": args, "children": children, "id": uid()}

def text_event(lines):
    return {"command": "EVENT_TEXT", "args": text_args(lines), "id": uid()}

def value_switch(var, cases, default_body):
    """EVENT_SWITCH on `var`; cases = list of (int_value, body). Chains in 16s.
    `default_body` is the else branch (used once, in the deepest switch)."""
    chunk, rest = cases[:16], cases[16:]
    args = {"variable": var, "choices": len(chunk), "__collapseElse": False}
    for i in range(16):
        args[f"__collapseCase{i}"] = False
    for i, (val, _) in enumerate(chunk):
        args[f"value{i}"] = {"type": "number", "value": val}
    children = {f"true{i}": body for i, (_, body) in enumerate(chunk)}
    children["false"] = [value_switch(var, rest, default_body)] if rest else default_body
    return {"command": "EVENT_SWITCH", "args": args, "children": children, "id": uid()}

def area_body(scene, area_lines):
    """Body for one area: a switch on the sign's X tile (var 12); for X values
    shared by >1 sign, a nested switch on the Y tile (var 13). Unmatched signs
    fall through to the area/town sign."""
    fb = lambda: [text_event(area_lines)]          # fresh fallback (unique ids)
    signs = SCENE_SIGNS.get(scene, [])
    if not signs:
        return fb()
    groups = {}                                    # x -> [(y, lines), ...]
    for x, y, lines in signs:
        groups.setdefault(x, []).append((y, lines))
    txt = lambda lines: [text_event(lines)] if lines else fb()  # None -> area sign
    x_cases = []
    for x, ys in groups.items():
        if len(ys) == 1:
            body = txt(ys[0][1])
        else:
            y_cases = [(y, txt(lines)) for y, lines in ys]
            body = [value_switch("13", y_cases, fb())]
        x_cases.append((x, body))
    return [value_switch("12", x_cases, fb())]

def write_read_area_sign():
    cases = []
    for num, (scene, lines) in enumerate(AREAS, start=1):
        cases.append((num, area_body(scene, lines)))
    doc = {
        "_resourceType": "script",
        "id": READ_SIGN_ID,
        "name": "Read Area Sign",
        "description": "Shows a signboard message for the Sign the player faces. "
                       "Switches on CurrentArea (var 22, set by each scene's On Init), "
                       "then on the sign's X tile (PlayerX var12); where several signs "
                       "share an X, a nested switch on the Y tile (PlayerY var13) picks "
                       "the right one. Unmatched signs fall through to the area sign. "
                       "Called from the overworld A-button handler when the player "
                       "faces a Sign metatile (id 125).",
        "variables": {},
        "actors": {},
        "symbol": "script_read_area_sign",
        "script": [build_switch(cases)],
    }
    save(os.path.join(ROOT, "scripts", "read_area_sign.gbsres"), doc)

# --------------------------------------------------------------- 3. init A-handler hook
def find_input_a_true(node):
    """Return the children.true list of the EVENT_SET_INPUT_SCRIPT for 'a'."""
    if isinstance(node, dict):
        if node.get("command") == "EVENT_SET_INPUT_SCRIPT" and \
           node.get("args", {}).get("input") == ["a"]:
            return node["children"]["true"]
        for v in node.values():
            r = find_input_a_true(v)
            if r is not None:
                return r
    elif isinstance(node, list):
        for it in node:
            r = find_input_a_true(it)
            if r is not None:
                return r
    return None

def hook_init():
    f = os.path.join(ROOT, "scripts", "init_overworld_script.gbsres")
    d = load(f)
    true_list = find_input_a_true(d["script"])
    assert true_list is not None, "could not find A-button input handler"
    # Drop any previously-inserted SIGN branch so this stays idempotent.
    def is_sign_if(ev):
        return ev.get("command") == "EVENT_IF" and \
            ev.get("args", {}).get("condition", {}).get("valueB", {}).get("value") == SIGN_CONST
    true_list[:] = [ev for ev in true_list if not is_sign_if(ev)]
    sign_if = {
        "command": "EVENT_IF",
        "args": {
            "condition": {
                "type": "eq",
                "valueA": {"type": "variable", "value": "0"},
                "valueB": {"type": "constant", "value": SIGN_CONST},
            },
            "__collapseElse": True,
        },
        "children": {
            "true": [{
                "command": "EVENT_CALL_CUSTOM_EVENT",
                "args": {"customEventId": READ_SIGN_ID},
                "id": uid(),
            }],
            "false": [],
        },
        "id": uid(),
    }
    # insert directly after EVENT_GET_META_TILE_AT_POS (var 0 = metatile in front)
    pos = next((i for i, ev in enumerate(true_list) if ev.get("id") == GET_MT_ID), None)
    insert_at = pos + 1 if pos is not None else len(true_list)
    true_list.insert(insert_at, sign_if)
    save(f, d)
    return "hooked"

# ----------------------------------------------------- 4. set CurrentArea per scene
def set_scene_areas():
    n = 0
    for num, (scene, _) in enumerate(AREAS, start=1):
        f = os.path.join(ROOT, "scenes", scene, "scene.gbsres")
        d = load(f)
        script = d.get("script", [])
        existing = next((ev for ev in script
                         if ev.get("command") == "EVENT_SET_VALUE"
                         and ev.get("args", {}).get("variable") == AREA_VAR), None)
        if existing:
            existing["args"]["value"] = {"type": "number", "value": num}
        else:
            script.insert(0, {
                "command": "EVENT_SET_VALUE",
                "args": {"variable": AREA_VAR, "value": {"type": "number", "value": num}},
                "id": uid(),
            })
            d["script"] = script
        save(f, d)
        n += 1
    return n

print("variable:", ensure_variable())
write_read_area_sign()
print("read_area_sign.gbsres written with", len(AREAS), "areas")
print("init hook:", hook_init())
print("scenes set:", set_scene_areas())
