/**
 * populate_scenes.js
 * ------------------
 * Places actor instances (referencing generated prefabs) into the 40 target
 * Pokemon overworld scenes in this project.
 *
 * Usage:
 *   node populate_scenes.js            # place actors in all target scenes
 *   node populate_scenes.js --dry-run  # print placement plan, write no files
 *
 * Prerequisites:
 *   Run generate_sprites.js first to produce tools/sprite_ids.json.
 *
 * Actor file format:
 *   GBS 4.x stores each actor as a separate file:
 *     project/scenes/{sceneName}/actors/{actorName}.gbsres
 *
 * Placement rules:
 *   - Each scene receives 2..4 actors (random, capped at scene size)
 *   - NPC characters (60%), Pokémon (25%), objects (15%) weight distribution
 *   - Positions use coordinateType "tiles" with even x,y (16px-grid aligned)
 *   - 2-tile padding from scene edges
 *   - No two actors placed at the same tile position
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const crypto = require('crypto');

// ─────────────────────────────────────────────────────────────
// Paths
// ─────────────────────────────────────────────────────────────
const PROJECT_ROOT   = path.join(__dirname, '..');
const SCENES_DIR     = path.join(PROJECT_ROOT, 'project', 'scenes');
const SPRITE_IDS_IN  = path.join(__dirname, 'sprite_ids.json');

// ─────────────────────────────────────────────────────────────
// Target scenes (all Pokemon overworld scenes in the project)
// ─────────────────────────────────────────────────────────────
const TARGET_SCENES = [
  'palette_town',
  'route_1',  'route_2',  'route_3',  'route_4',  'route_5',
  'route_6',  'route_7',  'route_8',  'route_9',  'route_10',
  'route_11', 'route_12', 'route_12_a', 'route_12_b',
  'route_13', 'route_14', 'route_15', 'route_16',
  'route_17a', 'route_17b',
  'route_18', 'route_19', 'route_20', 'route_21',
  'route_22', 'route_23_a', 'route_23_b', 'route_24', 'route_25',
  'viridian_city', 'pewter_city', 'cerulean_city', 'vermillion_city',
  'celadon_city', 'saffron_city', 'lavender_town', 'fuchsia_city',
  'cinabar_island', 'indigo_plateau',
];

// Actors per scene (min, max)
const ACTORS_MIN = 2;
const ACTORS_MAX = 4;

// Edge padding in tiles
const EDGE_PAD = 2;

// ─────────────────────────────────────────────────────────────
// Deterministic seeded random (mulberry32)
// Using a seed so results are reproducible; change seed for variety
// ─────────────────────────────────────────────────────────────
let _seed = 0x6b5f3c7a;
function seededRand() {
  _seed |= 0;
  _seed = _seed + 0x6d2b79f5 | 0;
  let t = Math.imul(_seed ^ (_seed >>> 15), 1 | _seed);
  t = t + Math.imul(t ^ (t >>> 7), 61 | t) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
function randInt(min, max) { return Math.floor(seededRand() * (max - min + 1)) + min; }
function randFrom(arr) { return arr[Math.floor(seededRand() * arr.length)]; }

function uuid() { return crypto.randomUUID(); }

// ─────────────────────────────────────────────────────────────
// Weighted random character selection
// ─────────────────────────────────────────────────────────────
function buildWeightedPool(spriteIds) {
  const pool = [];
  for (const [name, info] of Object.entries(spriteIds)) {
    // NPC=6 weight, pokemon=2.5 weight (→3), object=1.5 weight (→2)
    const w = info.type === 'npc' ? 6 : info.type === 'pokemon' ? 3 : 2;
    for (let i = 0; i < w; i++) pool.push({ name, ...info });
  }
  return pool;
}

// ─────────────────────────────────────────────────────────────
// Actor instance builder
// ─────────────────────────────────────────────────────────────
function makeActorInstance(name, prefabId, spriteId, x, y, idx) {
  // Symbol: must be a valid C identifier, unique within the project
  const shortSym = name.replace(/[^a-z0-9]/g, '_').slice(0, 12);
  const symbol   = `npc_${shortSym}_${idx.toString(16).padStart(4, '0')}`;

  return {
    _resourceType: "actor",
    _index:        idx,
    id:            uuid(),
    symbol,
    prefabId,
    name,
    coordinateType: "tiles",
    x,
    y,
    frame:          0,
    animate:        true,
    spriteSheetId:  spriteId,
    paletteId:      "",
    direction:      "down",
    moveSpeed:      1,
    animSpeed:      15,
    isPinned:       false,
    persistent:     false,
    collisionGroup: "",
    collisionExtraFlags:     [],
    prefabScriptOverrides:   {},
    script:       [],
    startScript:  [],
    updateScript: [],
    hit1Script:   [],
    hit2Script:   [],
    hit3Script:   [],
  };
}

// ─────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────

function main() {
  const dryRun = process.argv.includes('--dry-run');

  // Load sprite IDs generated by generate_sprites.js
  if (!fs.existsSync(SPRITE_IDS_IN)) {
    console.error('ERROR: tools/sprite_ids.json not found. Run generate_sprites.js first.');
    process.exit(1);
  }
  const spriteIds = JSON.parse(fs.readFileSync(SPRITE_IDS_IN, 'utf8'));
  const pool = buildWeightedPool(spriteIds);
  console.log(`Loaded ${Object.keys(spriteIds).length} characters. Pool size: ${pool.length}`);

  let totalActors = 0;
  let totalScenes = 0;
  let globalActorIdx = 0;

  for (const sceneName of TARGET_SCENES) {
    const sceneDir  = path.join(SCENES_DIR, sceneName);
    const sceneFile = path.join(sceneDir, 'scene.gbsres');

    if (!fs.existsSync(sceneFile)) {
      console.warn(`  [SKIP] ${sceneName}: scene.gbsres not found`);
      continue;
    }

    // Read scene dimensions
    const sceneData = JSON.parse(fs.readFileSync(sceneFile, 'utf8'));
    const sceneW = sceneData.width  || 20;
    const sceneH = sceneData.height || 20;

    // Compute valid placement grid (even positions, 2-tile padding)
    const minX = EDGE_PAD;
    const maxX = sceneW - EDGE_PAD - 1;
    const minY = EDGE_PAD;
    const maxY = sceneH - EDGE_PAD - 1;

    if (maxX < minX + 2 || maxY < minY + 2) {
      console.warn(`  [SKIP] ${sceneName}: scene too small (${sceneW}×${sceneH})`);
      continue;
    }

    // Pick number of actors for this scene
    const count = randInt(ACTORS_MIN, ACTORS_MAX);
    const used  = new Set();

    const actors = [];
    let attempts = 0;
    while (actors.length < count && attempts < 200) {
      attempts++;
      // Even positions for 16px-grid alignment
      const x = Math.floor(randInt(minX, maxX) / 2) * 2;
      const y = Math.floor(randInt(minY, maxY) / 2) * 2;
      const key = `${x},${y}`;
      if (used.has(key)) continue;
      used.add(key);

      const char = randFrom(pool);
      actors.push({ char, x, y });
    }

    console.log(`${dryRun ? '[DRY] ' : ''}${sceneName} (${sceneW}×${sceneH}): placing ${actors.length} actors`);
    actors.forEach(a => console.log(`  → ${a.char.name} @ (${a.x}, ${a.y})`));

    if (!dryRun) {
      const actorsDir = path.join(sceneDir, 'actors');
      fs.mkdirSync(actorsDir, { recursive: true });

      // Track names used in this scene for uniqueness
      const sceneNameCount = {};
      for (const { char, x, y } of actors) {
        const baseName = char.name;
        sceneNameCount[baseName] = (sceneNameCount[baseName] || 0) + 1;
        const instanceName = sceneNameCount[baseName] > 1
          ? `${baseName}_${sceneNameCount[baseName]}`
          : baseName;

        const instance = makeActorInstance(
          instanceName,
          char.prefabId,
          char.spriteId,
          x, y,
          globalActorIdx++,
        );

        // Actor filename: name → lowercase, spaces→underscores, slashes→underscores
        const filename = instanceName.toLowerCase().replace(/\s+/g, '_').replace(/[/\\]/g, '_') + '.gbsres';
        fs.writeFileSync(path.join(actorsDir, filename), JSON.stringify(instance, null, 2));
      }
    }

    totalActors += actors.length;
    totalScenes++;
  }

  console.log(`\n${ dryRun ? 'DRY RUN — ' : '' }Done: ${totalActors} actors across ${totalScenes} scenes`);
  if (dryRun) console.log('Re-run without --dry-run to write files.');
}

main();
